//
//  TB_Latefee.m
//  Hpi-FDS
//
//  Created by bin tang on 12-7-26.
//  Copyright (c) 2012年 Landscape. All rights reserved.
//

#import "TB_Latefee.h"

@implementation TB_Latefee

@synthesize DISPATCHNO,PORTCODE,FACTORYCODE,FEERATE,ALLOWPERIOD,TRADE,KEYVALUE,TRIPNO,TRADETIME,P_ANCHORAGETIME,P_DEPARTTIME,P_CONFIRM,P_CONUSER,P_CONTIME,
F_ANCHORAGETIME,F_DEPARTTIME,F_CONFIRM,F_CONTIME,F_CONUSER,LATEFEE,P_CORRECT,P_NOTE,F_CORRECT,F_NOTE,ISCAL,CURRENCY,EXCHANGERATE,PORTNAME, FACTORYNAME,  COMPANY,SHIPNAME, SUPPLIER ,COALTYPE; 
@synthesize COMID,SHIPID,LW ,SUPID,TYPEID;


@end
